import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  courseSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '📖 Course Overview',
    },
    {
      type: 'category',
      label: '🧱 Tier 1 — Foundations',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'tier-1-foundations' }],
    },
    {
      type: 'category',
      label: '🔧 Tier 2 — Builder',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'tier-2-builder' }],
    },
    {
      type: 'category',
      label: '🚀 Tier 3 — Advanced',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'tier-3-advanced' }],
    },
    {
      type: 'category',
      label: '🏗️ Tier 4 — Architect',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'tier-4-architect' }],
    },
  ],
};

export default sidebars;
